import type { Metadata } from "next";
import { Bowlby_One_SC, Geist, Geist_Mono, Alex_Brush } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const bowlby = Bowlby_One_SC({
  variable: "--font-bowlby",
  subsets: ['latin'],
  weight: '400',
})

const alexBrush = Alex_Brush({
  variable: "--font-alex-brush",
  subsets: ['latin'],
  weight: '400',
})

export const metadata: Metadata = {
  title: "Pizza Planet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${bowlby.variable} ${alexBrush.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
